spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 1721373535
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
